//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaborLedce.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaborLedce.Assets.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba připojení.
        /// </summary>
        internal static string ChybaPripojeni {
            get {
                return ResourceManager.GetString("ChybaPripojeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hystorie zadání.
        /// </summary>
        internal static string HystorieZadani {
            get {
                return ResourceManager.GetString("HystorieZadani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram fotky.
        /// </summary>
        internal static string InstagramFotky {
            get {
                return ResourceManager.GetString("InstagramFotky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEJNOVĚJŠÍ FOTKY.
        /// </summary>
        internal static string InstagramPhotos {
            get {
                return ResourceManager.GetString("InstagramPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodařilo se načíst fotky z táborového instagramu. .
        /// </summary>
        internal static string M001 {
            get {
                return ResourceManager.GetString("M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morseovka.
        /// </summary>
        internal static string Morseovka {
            get {
                return ResourceManager.GetString("Morseovka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        internal static string Oaplikaci {
            get {
                return ResourceManager.GetString("Oaplikaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PŘEKLADAČ.
        /// </summary>
        internal static string Prekladac {
            get {
                return ResourceManager.GetString("Prekladac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rostliny.
        /// </summary>
        internal static string Rostliny {
            get {
                return ResourceManager.GetString("Rostliny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text pro překlad.
        /// </summary>
        internal static string TextProPreklad {
            get {
                return ResourceManager.GetString("TextProPreklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vymazat.
        /// </summary>
        internal static string Vymazat {
            get {
                return ResourceManager.GetString("Vymazat", resourceCulture);
            }
        }
    }
}
